### ISSUE TITLE
fetch_instancart is broken

### ISSUE THREAD

**Issue by remiadon** [scikit-mine/scikit-mine#113]
**Describe the bug**
The current method crashes
The target server returns a huge dataset (300mb)

We should download our own processed version
more local processing is prone to more errors
and waiting times due to data size

**To Reproduce**
A minimal example to reproduce the behaviour:
```python
from skmine.datasets import 
insta = fetch_instacart()
```

**FIX**
another dump is available here https://data.world/datasets/instacart
use zenodo as in https://github.com/scikit-mine/scikit-mine/pull/112 and download from there

**Comment by hermann74** [comment]
Remove instacart dataset from skmine  because link for direct download is broken ([https://www.instacart.com/datasets/grocery-shopping-2017](https://www.instacart.com/datasets/grocery-shopping-2017)). People can download it via Kaggle account : [https://www.kaggle.com/c/instacart-market-basket-analysis/data](https://www.kaggle.com/c/instacart-market-basket-analysis/data)
