### ISSUE TITLE
Emerging patterns -- inclusion or not ?

### ISSUE THREAD

**Issue by remiadon** [scikit-mine/scikit-mine#48]
#### Describe the workflow you want to enable
Some internal discussions have raised attention for Emerging Patterns
On the long term we have to provide not only models but also methodologies to perform classification, so emerging patterns might be a solution

#### Describe your proposed solution
a new module called ``emerging`` providing a set of tools to deal with emerging pattern, jumping emerging patterns, and so on.

#### Additional context
[This paper](https://people.eng.unimelb.edu.au/baileyj/papers/ajcai03.pdf) is a good place to start

Note that section 6.3 (Pairwise classification) looks very much like [sklearn OneVsOneClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.multiclass.OneVsOneClassifier.html) methodology

**Comment by remiadon** [comment]
@alexandre-termier @PeggyCellier what do you think ?

**Comment by alexandre-termier** [comment]
Yes, we definitely need emerging patterns, so OK for the `emerging` module.
Since the inception of scikit-mine we want to have DiffNorm (which does emerging patterns with MDL pattern set selection), or the newest approach of the group of J. Vreeken (https://eda.mmci.uni-saarland.de/prj/disc/).

Now it could also be discussed to have a non-MDL, non pattern-set emerging pattern miner, like we have LCM for itemsets. 
The rationale could be here that for certain tasks people may prefer to have their own filter to postprocess emerging patterns. 
And there is no good public implementation of emerging pattern mining, this is a recurrent problem in the team. 

About references: for emerging patterns, the works of Guozhu Dong must be looked at in priority (https://dblp.uni-trier.de/pers/d/Dong:Guozhu.html). 
He initiated the domain with the paper from 1999 : 

Guozhu Dong, Jinyan Li: _Efficient Mining of Emerging Patterns: Discovering Trends and Differences_. KDD 1999: 43-52  -> https://dl.acm.org/doi/10.1145/312129.312191
