### ISSUE TITLE
User test -- pip install

### ISSUE THREAD

**Issue by remiadon** [scikit-mine/scikit-mine#67]
First tests crashed on Windows,

check new versions work

**Comment by remiadon** [comment]
https://github.com/scikit-mine/scikit-mine/issues/38

https://github.com/scikit-mine/scikit-mine/issues/59

**Comment by remiadon** [comment]
@alexandre-termier @PeggyCellier any update on this ?
Can you try running `pip install scikit-mine` on your machine and report results here ?

**Comment by alexandre-termier** [comment]
@remiadon The problem was caused by the roaringbitmaps package that requires a C compiler. I installed Visual Studio on my machine and retried the installed: it then worked smoothly.

**Comment by PeggyCellier** [comment]
@remiadon The problem was about joblib:
"ERROR: Cannot uninstall 'joblib'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."

To fix it, I upgraded joblib by installing a new version ignoring the previous installed:
pip install --ignore-installed joblib

Now scikit-mine is installed!
