### ISSUE TITLE
When I retrieve class labels using fetch_mushroom, the original labels can still be found in the dataset.

### ISSUE THREAD

**Issue by sdall** [scikit-mine/scikit-mine#79]
```python
D, y = fetch_mushroom(return_D_y=True)
```
results in a dataset D that contains the original class labels.

If `return_D_y=True`, I expect that `D` does not contain any items that encode class labels

Because I happen to know the dataset, a possible workaround is
```python 
x = [[i for i in x if i not in [1,2]] for x in D]
```

**Comment by remiadon** [comment]
On my side I get this 
```python
>> from skmine.datasets.fimi import fetch_mushroom
>> from itertools import chain
>> D, y = fetch_mushroom(return_D_y=True)
>> sum((1 for _ in chain(*D) if _ in {1, 2}))
0
```

How did you install scikit-mine ? if you pip installed it you probably have version 1.0.0, which included this bug
Please make pip install point to the current repo `pip install https://github.com/scikit-mine/scikit-mine`, or even better, git clone the current repo

I'll update the CI so that the official doc is built when we deploy a new version

**Comment by sdall** [comment]
I am sorry, I should have double checked the default branch. :)
