### ISSUE TITLE
Depth Limit for LCM

### ISSUE THREAD

**Issue by lgalarra** [scikit-mine/scikit-mine#89]
#### Describe the workflow you want to enable
I am implementing an algorithm that is using LCM to mine closed itemsets. However, I do not need LCM to mine ALL closed patterns above the support, but only those patterns up to a certain depth. While this is achievable as a post-processing step, it is inefficient and cumbersome (since the size of the itemset does not necessarily provide its depth in the search space). Moreover, it might be nice to have the depth of a pattern as output of LCM (let me know if this should go in a different feature request).

#### Describe your proposed solution
I would propose to extend the LCM constructor with an argument `max_depth` and use it as a criterion to stop or continue the search in a particular branch.

**Comment by remiadon** [comment]
Hi @lgalarra ,
really nice suggestion 💯 

I was already considering implementing a `max_length` parameter (which is related to the `max_depth`, as we operate by extending itemsets of smaller size). 

However I think `max_depth` is more robust because:
1) It cuts the search space in a more understandable way (for **developers**) and has a more interesting mathematical background than `max_length` (for **researchers**)
2) resulting patterns are returned via pandas, filtering those results by length is already easy for **users**
3) It's fully compatible with the `min_supp` parameter.  

I was planning to work on improving LCM performances, I should be able to get a nice version quickly,
running benchmarks with [asv](https://asv.readthedocs.io/en/stable/)

I'll submit a PR and add you as a reviewer, if you have a little bit of time, you could run the benchmark suite on your local machine

What do you think ?

**Comment by remiadon** [comment]
Oh and @lgalarra yes we can provide the depth of a pattern in the output. In the functional definitions of skmine (which I'll publish someday hopefully), the discover function is the only one that accepts non-data calling arguments (unlinke fit, transform, predicts, etc..). This is designed for exploratory analysis so any numerical extra information is welcome in the ouput of `discover`

**Comment by lgalarra** [comment]
> I'll submit a PR and add you as a reviewer, if you have a little bit of time, you could run the benchmark suite on your local machine
> 
> What do you think ?

Sure!

> This is designed for exploratory analysis, so any numerical extra information is welcome in the ouput of discover

If I understand correctly, this is the function that will always change for accepting new attributes in the output.

> (which is related to the max_depth, as we operate by extending itemsets of smaller size)

Actually `max_depth` may be useful in some scenarios. It is also more "user-friendly", if we assume the user sees LCM as a black-box. Unlike `max_depth`, it must be applied on per-pattern basis after computing the closure.

**Comment by remiadon** [comment]
> if I understand correctly, this is the function that will always change for accepting new attributes in the output.

Exactly, but I think we can restrict this to boolean values (like output it or not). In this case `max_depth` set when creating the model, but including this information would be allowed when calling `discover`. IMO this is a good compromise

I'll set a `max_depth` of 20 by default, with a root having a depth of 1
Is that all right ?

**Comment by remiadon** [comment]
Oh and i'll probably force pandas Series as input, which remains a source of unwanted error

**Comment by lgalarra** [comment]
I think max_depth should be set by default to something such as "None", "-1" of "maxint" to indicate no depth limit.
